services:
  # Notes API service with in-memory storage
  notes-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-api-memory
    environment:
      - STORAGE_TYPE=memory
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - notes-network
    restart: on-failure

# Networks
networks:
  notes-network:
    driver: bridge
